# Generated by Django 4.0.4 on 2022-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userCarpools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=90)),
                ('to', models.CharField(max_length=90)),
                ('brand', models.TextField()),
                ('carNo', models.TextField(max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('color', models.TextField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('gender', models.TextField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('pin', models.IntegerField()),
                ('drivelic', models.CharField(max_length=90)),
                ('drivelicpic', models.FileField(upload_to='')),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
