# Generated by Django 4.0.4 on 2022-10-13 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercarpools',
            name='poolDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='usercarpools',
            name='poolTime',
            field=models.TimeField(default=datetime.time),
        ),
    ]
